language: node_js
sudo: false
node_js:
 - "0.10"

addons:
  sauce_connect:
    no_ssl_bump_domains: all

env:
 global:
   - secure: Xwxk85Yw/Rnwl39ignJixsT+Q8t3Qw3iVdOg0GqEoHoU6yv1VEQTVXZMmWDXuGRH7PEUQQv5m3P3piU36NVMu+LkMZN8HZXA4oFgUlLqKDg8NwVht113KJhfU8IlaF5lFElSx/pHV+TM+/Sx/9RmsZ0Gv0kBta7//+Nllar4qQ0=
   - secure: JyoPpXiWwP4266WebKqEUHc+fY5JM2YAYzeT+OMwqi4Lf2zsiAu+rMGBRtfBh3wDaFkOfH55bKz4t1C+wH5XZu1VctYCJVdOl7XpY0dBUwANCr6N/CXNq9bJzGXnpzLKUfDt/W/5h1BV4T8Km8TJZr7VlCx0EpvZlS3zP9Z3YJI=

before_script:
 - npm install
 - ./node_modules/.bin/bower install
 - ./node_modules/.bin/grunt

script:
 - karma start karma.sauce.conf.js

before_install:
  - npm install -g karma-cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
 - ./node_modules/.bin/lcov-result-merger '.coverage/**/lcov.info' .coverage/lcov.info
 - ./node_modules/.bin/coveralls < .coverage/lcov.info

